"""initial_schema

Schéma créé en local via ``python scripts/bootstrap_db.py`` (create_all ORM).
Cette révision est vide : sert de point de départ Alembic après ``alembic stamp e8c2aea87d0c``.

Revision ID: e8c2aea87d0c
Revises:
Create Date: 2026-04-12 02:06:35.053910
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c2aea87d0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
